### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'config'

### ISSUE THREAD

**Issue by KangChou** [SVAIGBA/WMSeg#14]
- UBUNTU16.04 
- PYTHON3.6
```

# of word in train: 55304: 
# of n-gram in memory: 71499
Traceback (most recent call last):
  File "wmseg_main.py", line 677, in <module>
    main()
  File "wmseg_main.py", line 667, in main
    train(args)
  File "wmseg_main.py", line 101, in train
    seg_model = WMSeg(word2id, gram2id, label_map, hpara, args)
  File "/data/my_project/nlp_text/WMSeg/wmseg_model.py", line 98, in __init__
    self.hpara['config'] = self.bert.config
AttributeError: 'NoneType' object has no attribute 'config'
```

**Comment by YingZhuY** [comment]
你需要在 bert 预训练模型同目录下加个 config.json 文件

![bert](https://user-images.githubusercontent.com/53252781/170252724-bff96dac-6e1a-41b4-bf80-e9ffa99cfc73.PNG)

比如我用的 [bert-base-chinese](https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-chinese-config.json) 就是
```json
{
  "attention_probs_dropout_prob": 0.1, 
  "directionality": "bidi", 
  "hidden_act": "gelu", 
  "hidden_dropout_prob": 0.1, 
  "hidden_size": 768, 
  "initializer_range": 0.02, 
  "intermediate_size": 3072, 
  "max_position_embeddings": 512, 
  "num_attention_heads": 12, 
  "num_hidden_layers": 12, 
  "pooler_fc_size": 768, 
  "pooler_num_attention_heads": 12, 
  "pooler_num_fc_layers": 3, 
  "pooler_size_per_head": 128, 
  "pooler_type": "first_token_transform", 
  "type_vocab_size": 2, 
  "vocab_size": 21128
}
```
具体方法可参考 [此博客](https://blog.csdn.net/season77us/article/details/104311195)
